variable "public_key" {
  type = string
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDASNJB6+oZ8lfKaB+pwQRLckdpUSpYx0Q33vdOUo1LlomyuEczBzUb5Lcv5UyrC66rdb+LAppLszdQQfgxrt0Gg4SYUFRbfboSfVXOk7/50Cmz10qSJjGgwbAgOYuq+TE7NKEL0nTCWqpDlKfqaXfDI7GEBr5gFALvP2E8+VUT+X7gNOiSwZQJTnRHR1BvlGW+mETaQKAiayASbdKhQQniyjQtAcgd96aIQdFLx7lGnKqNfS+89/FY9oW2gW8tnt4DBba+DJ3A96c+s+yKfrMBpLQBWGwBUu3+RtrUSpj1oBLFUzKqv6D9UJnoCSYSf6IhK3sbayfO17Zl25Iqtr9T Generated By Termius"
}

variable "avail_zone" {
  type = string
  default = "us-east-1a"
}

variable "vpc_ep_svc_name" {
  type = string
  default = "com.amazonaws.us-east-1.s3"
}

variable "config-NetworkMiner" {
  default = "NetworkMiner.desktop"
}

variable "config-45-allow-colord" {
  default = "45-allow-colord.sh"
}
